had my first success as after i manually fixed the bootstrapping it worked and i was able to install various software. also the /nix/store overwrite seems to work. still this bug where:
1 % nix-channel --update
fetching list of Nix archives at `http://nixos.org/releases/nixpkgs/channels/nixpkgs-unstable/MANIFEST.bz2'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 64 8885k   64 5686k    0     0   390k      0  0:00:22  0:00:14  0:00:08  445k^Ccannot pull cache manifest from `http://nixos.org/releases/nixpkgs/channels/nixpkgs-unstable' at
/tmp/nix-unified/bin/nix-channel line 94.

2 % nix-channel --update
fetching list of Nix archives at `http://nixos.org/releases/nixpkgs/channels/nixpkgs-unstable/MANIFEST.bz2'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8885k  100 8885k    0     0   392k      0  0:00:22  0:00:22 --:--:--  507k
25648 store paths in manifest
downloading Nix expressions from `http://nixos.org/releases/nixpkgs/channels/nixpkgs-unstable/nixexprs.tar.bz2'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3340k  100 3340k    0     0   432k      0  0:00:07  0:00:07 --:--:--  493k
unpacking channel Nix expressions...
the following derivations will be built:
  /nix/store/0zqp1vinf4drn58yws2bf6gvcfyww2s4-channels.drv
building path(s) `/nix/store/az5xvcpbzji84v1cw6rl1q7agrz82dxd-channels'
build error: executing `/nix/store/q92pj3ggbsn98ax5kpvqsrhb3ly0gnhn-unpack.sh': Permission denied
builder for `/nix/store/0zqp1vinf4drn58yws2bf6gvcfyww2s4-channels.drv' failed with exit code 1
error: build of `/nix/store/0zqp1vinf4drn58yws2bf6gvcfyww2s4-channels.drv' failed
cannot unpack the channels at /tmp/nix-unified/bin/nix-channel line 128.
nix-channel --update  11.67s user 0.65s system 28% cpu 43.345 total

for some unknown reason /nix/store/q92pj3ggbsn98ax5kpvqsrhb3ly0gnhn-unpack.sh is not marked executable...?

diff --git a/test b/test
--- a/test
+++ b/test
@@ -2,50 +2,34 @@
 # helps to see compiler / linker stuff, just uncomment 
 #export VERBOSE=1
 
+NIXPATH="/tmp/nix-unified"
+#NIXPATH="/tmp/nix-cmake"
+
 #clean
 mkdir -p build
-cd /home/meli/Desktop/nix/nix-0.16-cmake && rm -Rf build/* && rm -Rf /tmp/nix-cmake/*  && rm -Rf /tmp/nix-destdir/* && cd build 
+cd /home/meli/Desktop/nix/nix-0.16-cmake && rm -Rf build/* && rm -Rf /tmp/nix-cmake/* && cd build 
 
 if [ $? -eq 0 ]; then
-NIXPATH="/tmp/nix-cmake"
-NIXDESTDIR="/tmp/nix-destdir"
-cmake -DCMAKE_INSTALL_PREFIX:PATH="${NIXPATH}" .. && make install | tee -a cmake_make_debug && make install DESTDIR=${NIXDESTDIR} | tee -a cmake_make_destdir_debug
-if [ $? -eq 0 ]; then
-
-echo "=========== BEGIN list of runtime path adaptions of cmake's 'make install' ============"
-grep "Set runtime path of" cmake_make_debug 
-echo "=========== BREAK list of runtime path adaptions of cmake's 'make install DESTDIR=...' ============"
-grep "Set runtime path of" cmake_make_destdir_debug 
-echo "=========== END   list of runtime path adaptions of cmake ============"
-
-echo "=========== checking if the nix-env binary can find it's libraries for ${NIXPATH}/bin/nix-env ==========="
-ldd ${NIXPATH}/bin/nix-env 
-echo "=========== checking if the nix-env binary can find it's libraries for ${NIXDESTDIR}/${NIXPATH}/bin/nix-env ==========="
-ldd ${NIXDESTDIR}/${NIXPATH}/bin/nix-env
-
-echo "=========== let's see if all symlinks are in ${NIXPATH} ==========="
-ls -la ${NIXPATH}/state/nix/gcroots
-echo "=========== let's see if all symlinks are in ${NIXDESTDIR}/${NIXPATH} ==========="
-ls -la ${NIXDESTDIR}/${NIXPATH}/state/nix/gcroots
-
-echo "=========== executing the installed binary, should output --help something, in ${NIXPATH} ==========="
-${NIXPATH}/bin/nix-env 2>&1 | tee -a exec_test | grep -e '--help' 
-if [ $? -eq 0 ]; then
-	echo "success: ${NIXPATH}/bin/nix-env was executable"
-else
-	echo "fail: ${NIXPATH}/bin/nix-env was NOT executable"
-	cat exec_test
-fi
-
-echo "=========== executing the installed binary, should output --help something, in ${NIXDESTDIR}/${NIXPATH} ==========="
-${NIXDESTDIR}/${NIXPATH}/bin/nix-env 2>&1 | tee -a exec_test2 | grep -e '--help' 
-if [ $? -eq 0 ]; then
-	echo "success: ${NIXDESTDIR}/${NIXPATH}/bin/nix-env was executable"
-else
-	echo "fail: ${NIXDESTDIR}/${NIXPATH}/bin/nix-env was NOT executable"
-	cat exec_test2
-fi
-
-
-fi
+	cmake -DCMAKE_INSTALL_PREFIX:PATH="${NIXPATH}" -DOVERWRITE_DEFAULT_STORE_DIR=ON .. && make install | tee -a cmake_make_debug 
+	if [ $? -eq 0 ]; then
+	
+		echo "=========== BEGIN list of runtime path adaptions of cmake's 'make install' ============"
+		grep "Set runtime path of" cmake_make_debug 
+		echo "=========== END   list of runtime path adaptions of cmake ============"
+		
+		echo "=========== checking if the nix-env binary can find it's libraries for ${NIXPATH}/bin/nix-env ==========="
+		ldd ${NIXPATH}/bin/nix-env 
+		
+		echo "=========== let's see if all symlinks are in ${NIXPATH} ==========="
+		ls -la ${NIXPATH}/state/nix/gcroots
+		
+		echo "=========== executing the installed binary, should output --help something, in ${NIXPATH} ==========="
+		${NIXPATH}/bin/nix-env 2>&1 | tee -a exec_test | grep -e '--help' 
+		if [ $? -eq 0 ]; then
+			echo "success: ${NIXPATH}/bin/nix-env was executable"
+		else
+			echo "fail: ${NIXPATH}/bin/nix-env was NOT executable"
+			cat exec_test
+		fi
+	fi
 fi
